# Définition du Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-service
        image: client
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        ports:
        - containerPort: 3000  # Port sur lequel le conteneur écoute

---
# Définition du Service
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 3000       # Port sur lequel le service sera accessible
      targetPort: 3000  # Port sur lequel le conteneur écoute
      nodePort: 31515   # Port sur lequel le service sera accessible depuis l'extérieur

