# Deployment 


apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-clusterip-srv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: posts-clusterip-service
  template:
    metadata:
      labels:
        app: posts-clusterip-service
    spec:
      containers:
      - name: posts-clusterip-service
        image: posts
        imagePullPolicy: Never
        ports:
        - containerPort: 4000

---

#Service

apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts-clusterip-service
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP