apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: client-srv  # Nom du service Kubernetes
            port:
              number: 3000  # Port sur lequel le service écoute
